.TH "GCLOUD PREVIEW MANAGED-INSTANCE-GROUPS UPDATES" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_preview_managed-instance-groups_updates \- managed Instance Group Updater client
.SH "SYNOPSIS"
.HP
gcloud\ preview\ managed\-instance\-groups\ updates\ \fICOMMAND\fR [\fB\-\-api\-version\fR\ \fIAPI_VERSION\fR;\ default="v1beta2"] [\fB\-\-format\fR\ \fIFORMAT\fR] [\fB\-\-group\fR\ \fIGROUP\fR] [\fB\-\-help\fR] [\fB\-\-project\fR\ \fIPROJECT\fR] [\fB\-\-quiet\fR,\ \fB\-q\fR] [\fB\-h\fR]
.SH "DESCRIPTION"
.sp
Managed Instance Group Updater client\&.
.SH "FLAGS"
.PP
\fB\-\-group\fR \fIGROUP\fR
.RS 4
Managed instance group name\&.
.RE
.SS "GLOBAL FLAGS"
.PP
\fB\-\-api\-version\fR \fIAPI_VERSION\fR; default="v1beta2"
.RS 4
Optional API version\&.
.RE
.PP
\fB\-\-format\fR \fIFORMAT\fR
.RS 4
Specify a format for printed output\&. By default, a command\-specific human\-friendly output format is used\&. Setting this flag to one of the available options will serialize the result of the command in the chosen format and print it to stdout\&. Supported formats are:
json,
text,
yaml\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display detailed help\&.
.RE
.PP
\fB\-\-project\fR \fIPROJECT\fR
.RS 4
The Google Cloud Platform project name to use for this invocation\&. If omitted then the current project is assumed\&.
.RE
.PP
\fB\-\-quiet\fR, \fB\-q\fR
.RS 4
Disable all interactive prompts when running gcloud commands\&. If input is required, defaults will be used, or an error will be raised\&.
.RE
.PP
\fB\-h\fR
.RS 4
Print a summary help and exit\&.
.RE
.SH "COMMANDS"
.sp
\fICOMMAND\fR is one of the following:
.PP
\fBcancel\fR
.RS 4
Cancels an existing update\&.
.RE
.PP
\fBdescribe\fR
.RS 4
Gets information about a single managed instance group update\&.
.RE
.PP
\fBlist\fR
.RS 4
Lists all managed instance group updates in a given project\&.
.RE
.PP
\fBpause\fR
.RS 4
Pauses an existing update\&.
.RE
.PP
\fBrollback\fR
.RS 4
Rolls back an existing update\&.
.RE
.PP
\fBrollforward\fR
.RS 4
Rolls forward an existing update\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBpreview\fR component\&. See installing components if it is not installed\&.
