.TH "GCLOUD PREVIEW MANAGED-INSTANCE-GROUPS UPDATES ROLLBACK" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_preview_managed-instance-groups_updates_rollback \- rolls back an existing update
.SH "SYNOPSIS"
.HP
gcloud\ preview\ managed\-instance\-groups\ updates\ rollback\ \fIHANDLE\fR [\fB\-\-api\-version\fR\ \fIAPI_VERSION\fR;\ default="v1beta2"] [\fB\-\-format\fR\ \fIFORMAT\fR] [\fB\-\-group\fR\ \fIGROUP\fR] [\fB\-\-help\fR] [\fB\-\-project\fR\ \fIPROJECT\fR] [\fB\-\-quiet\fR,\ \fB\-q\fR] [\fB\-h\fR]
.SH "DESCRIPTION"
.sp
Rolls back the update in state ROLLING_FORWARD, ROLLING_BACK or PAUSED (fails if the update is in any other state)\&. No\-op if invoked in state ROLLED_BACK\&.
.sp
Rollback sets the template that the Managed Instance Group used before the update was started and gradually restarts back to the old template all instances that are running in the new template\&.
.SH "POSITIONAL ARGUMENTS"
.PP
\fIHANDLE\fR
.RS 4
Handle for a managed instance group update\&.
.RE
.SH "FLAGS"
.PP
\fB\-\-api\-version\fR \fIAPI_VERSION\fR; default="v1beta2"
.RS 4
Optional API version\&.
.RE
.PP
\fB\-\-format\fR \fIFORMAT\fR
.RS 4
Specify a format for printed output\&. By default, a command\-specific human\-friendly output format is used\&. Setting this flag to one of the available options will serialize the result of the command in the chosen format and print it to stdout\&. Supported formats are:
json,
text,
yaml\&.
.RE
.PP
\fB\-\-group\fR \fIGROUP\fR
.RS 4
Managed instance group name\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display detailed help\&.
.RE
.PP
\fB\-\-project\fR \fIPROJECT\fR
.RS 4
The Google Cloud Platform project name to use for this invocation\&. If omitted then the current project is assumed\&.
.RE
.PP
\fB\-\-quiet\fR, \fB\-q\fR
.RS 4
Disable all interactive prompts when running gcloud commands\&. If input is required, defaults will be used, or an error will be raised\&.
.RE
.PP
\fB\-h\fR
.RS 4
Print a summary help and exit\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBpreview\fR component\&. See installing components if it is not installed\&.
