.TH "GCLOUD PREVIEW DOCKER" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_preview_docker \- ==SUPPRESS==
.SH "SYNOPSIS"
.HP
gcloud\ preview\ docker [\fIEXTRA_ARGS\fR\ \&...] [\fB\-\-authorize_only\fR,\ \fB\-a\fR] [\fB\-\-docker\-host\fR\ \fIDOCKER_HOST\fR] [\fB\-\-format\fR\ \fIFORMAT\fR] [\fB\-\-help\fR] [\fB\-\-project\fR\ \fIPROJECT\fR] [\fB\-\-quiet\fR,\ \fB\-q\fR] [\fB\-\-server\fR\ \fISERVER\fR,\ \fB\-s\fR\ \fISERVER\fR;\ default="https://container\&.cloud\&.google\&.com"] [\fB\-h\fR]
.SH "DESCRIPTION"
.sp
The docker sub\-command of gcloud wraps docker commands, so that gcloud can inject the appropriate fresh authentication token into requests that interact with the docker registry\&. As commands are simply passed through to docker, see this for a full reference of command\-line options that can be supplied after the \(em  http://docs\&.docker\&.com/reference/commandline/cli/
.SH "POSITIONAL ARGUMENTS"
.PP
[\fIEXTRA_ARGS\fR \&...]
.RS 4
Arguments to pass to docker
.RE
.SH "FLAGS"
.PP
\fB\-\-authorize_only\fR, \fB\-a\fR
.RS 4
Configure docker authorization only, do not launch the docker command\-line
.RE
.PP
\fB\-\-docker\-host\fR \fIDOCKER_HOST\fR
.RS 4
The URL to connect to Docker Daemon\&. Format: tcp://host:port or unix:///path/to/socket\&.
.RE
.PP
\fB\-\-server\fR \fISERVER\fR, \fB\-s\fR \fISERVER\fR; default="https://container\&.cloud\&.google\&.com"
.RS 4
The address of the Google Cloud Registry
.RE
.SS "GLOBAL FLAGS"
.PP
\fB\-\-format\fR \fIFORMAT\fR
.RS 4
Specify a format for printed output\&. By default, a command\-specific human\-friendly output format is used\&. Setting this flag to one of the available options will serialize the result of the command in the chosen format and print it to stdout\&. Supported formats are:
json,
text,
yaml\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display detailed help\&.
.RE
.PP
\fB\-\-project\fR \fIPROJECT\fR
.RS 4
The Google Cloud Platform project name to use for this invocation\&. If omitted then the current project is assumed\&.
.RE
.PP
\fB\-\-quiet\fR, \fB\-q\fR
.RS 4
Disable all interactive prompts when running gcloud commands\&. If input is required, defaults will be used, or an error will be raised\&.
.RE
.PP
\fB\-h\fR
.RS 4
Print a summary help and exit\&.
.RE
.SH "EXAMPLES"
.sp
Pull the image \fIcontainer\&.cloud\&.google\&.com/my\-org/my\-image\fR from the docker registry: gcloud preview docker \(em pull container\&.cloud\&.google\&.com/my\-org/my\-image
.sp
Push the image \fIcontainer\&.cloud\&.google\&.com/foo/bar:baz\fR to our private docker registry\&. gcloud preview docker \(em push container\&.cloud\&.google\&.com/foo/bar:baz
.sp
Configure authentication, then simply use docker: gcloud preview docker \-\-authorize_only docker push container\&.cloud\&.google\&.com/foo/bar:baz
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBpreview\fR component\&. See installing components if it is not installed\&.
.sp
This command is an internal implementation detail and may change or disappear without notice\&.
