.TH "GCLOUD PREVIEW MANAGED-INSTANCE-GROUPS START-ROLLING-UPDATE" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_preview_managed-instance-groups_start-rolling-update \- starts a new rolling update
.SH "SYNOPSIS"
.HP
gcloud\ preview\ managed\-instance\-groups\ start\-rolling\-update\ \fIGROUP\fR [\fB\-\-api\-version\fR\ \fIAPI_VERSION\fR;\ default="v1beta2"] [\fB\-\-format\fR\ \fIFORMAT\fR] [\fB\-\-help\fR] [\fB\-\-max\-num\-concurrent\-instances\fR\ \fIMAX_NUM_CONCURRENT_INSTANCES\fR] [\fB\-\-num\-canary\-instances\fR\ \fINUM_CANARY_INSTANCES\fR] [\fB\-\-project\fR\ \fIPROJECT\fR] [\fB\-\-quiet\fR,\ \fB\-q\fR] [\fB\-\-sleep\-after\-instance\-restart\fR\ \fISLEEP_AFTER_INSTANCE_RESTART\fR] \fB\-\-template\fR\ \fITEMPLATE\fR [\fB\-h\fR]
.SH "DESCRIPTION"
.sp
A rolling update causes the service to gradually recreate your existing instances with the new template\&. You can increase the number of instances updated simultaneously with the \-\-max\-num\-concurrent\-instances flag\&.
.sp
If you are not sure you want to apply an update to all existing instances, you can use the \-\-num\-canary\-instances flag and the update will automatically be paused after updating the number of instances specified\&. Afterwards, you can decide whether to cancel or continue the update\&.
.sp
In case you notice your managed instance group misbehaving due to the new template, you can roll back the update\&. This will stop the update from being applied to more instances, and instances already created with the new template will be recreated with the last template applied before the current update\&.
.SH "POSITIONAL ARGUMENTS"
.PP
\fIGROUP\fR
.RS 4
Managed instance group name\&.
.RE
.SH "FLAGS"
.PP
\fB\-\-max\-num\-concurrent\-instances\fR \fIMAX_NUM_CONCURRENT_INSTANCES\fR
.RS 4
Maximum number of instances that can be updated simultaneously\&.
.RE
.PP
\fB\-\-num\-canary\-instances\fR \fINUM_CANARY_INSTANCES\fR
.RS 4
Number of instances updated as a part of canary phase\&.
.RE
.PP
\fB\-\-sleep\-after\-instance\-restart\fR \fISLEEP_AFTER_INSTANCE_RESTART\fR
.RS 4
Time period after the instance has been restarted but before marking the update of this instance as done\&. Valid units for this flag are
\fIs\fR
for seconds,
\fIm\fR
for minutes,
\fIh\fR
for hours and
\fId\fR
for days\&. If no unit is specified, seconds is assumed\&.
.RE
.PP
\fB\-\-template\fR \fITEMPLATE\fR
.RS 4
Name of the Compute Engine instance template resource\&.
.RE
.SS "GLOBAL FLAGS"
.PP
\fB\-\-api\-version\fR \fIAPI_VERSION\fR; default="v1beta2"
.RS 4
Optional API version\&.
.RE
.PP
\fB\-\-format\fR \fIFORMAT\fR
.RS 4
Specify a format for printed output\&. By default, a command\-specific human\-friendly output format is used\&. Setting this flag to one of the available options will serialize the result of the command in the chosen format and print it to stdout\&. Supported formats are:
json,
text,
yaml\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display detailed help\&.
.RE
.PP
\fB\-\-project\fR \fIPROJECT\fR
.RS 4
The Google Cloud Platform project name to use for this invocation\&. If omitted then the current project is assumed\&.
.RE
.PP
\fB\-\-quiet\fR, \fB\-q\fR
.RS 4
Disable all interactive prompts when running gcloud commands\&. If input is required, defaults will be used, or an error will be raised\&.
.RE
.PP
\fB\-h\fR
.RS 4
Print a summary help and exit\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBpreview\fR component\&. See installing components if it is not installed\&.
