.TH "GCLOUD PREVIEW MANAGED-INSTANCE-GROUPS DELETE-INSTANCES" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_preview_managed-instance-groups_delete-instances \- deletes one or more instances from a managed instance group
.SH "SYNOPSIS"
.HP
gcloud\ preview\ managed\-instance\-groups\ delete\-instances\ \fIGROUP\fR [\fB\-\-api\-version\fR\ \fIAPI_VERSION\fR;\ default="v1beta2"] [\fB\-\-format\fR\ \fIFORMAT\fR] [\fB\-\-help\fR] \fB\-\-instance\fR\ \fIINSTANCE\fR [\fIINSTANCE\fR\ \&...] [\fB\-\-project\fR\ \fIPROJECT\fR] [\fB\-\-quiet\fR,\ \fB\-q\fR] [\fB\-h\fR]
.SH "DESCRIPTION"
.sp
This command deletes one or more instances from a managed instance group\&. Once the instances have finished deleting, the size of the group is automatically reduced to reflect the changes\&.
.sp
If you would like to keep the underlying virtual machines but still remove them from the managed instance group, use the abandon\-instances command instead\&.
.SH "POSITIONAL ARGUMENTS"
.PP
\fIGROUP\fR
.RS 4
Managed instance group name\&.
.RE
.SH "FLAGS"
.PP
\fB\-\-instance\fR \fIINSTANCE\fR [\fIINSTANCE\fR \&...]
.RS 4
Names of the instances to delete\&.
.RE
.SS "GLOBAL FLAGS"
.PP
\fB\-\-api\-version\fR \fIAPI_VERSION\fR; default="v1beta2"
.RS 4
Optional API version\&.
.RE
.PP
\fB\-\-format\fR \fIFORMAT\fR
.RS 4
Specify a format for printed output\&. By default, a command\-specific human\-friendly output format is used\&. Setting this flag to one of the available options will serialize the result of the command in the chosen format and print it to stdout\&. Supported formats are:
json,
text,
yaml\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display detailed help\&.
.RE
.PP
\fB\-\-project\fR \fIPROJECT\fR
.RS 4
The Google Cloud Platform project name to use for this invocation\&. If omitted then the current project is assumed\&.
.RE
.PP
\fB\-\-quiet\fR, \fB\-q\fR
.RS 4
Disable all interactive prompts when running gcloud commands\&. If input is required, defaults will be used, or an error will be raised\&.
.RE
.PP
\fB\-h\fR
.RS 4
Print a summary help and exit\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBpreview\fR component\&. See installing components if it is not installed\&.
