.TH "GCLOUD PREVIEW DEPLOYMENT-MANAGER DEPLOYMENTS" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_preview_deployment-manager_deployments \- commands for Deployment Manager deployments
.SH "SYNOPSIS"
.HP
gcloud\ preview\ deployment\-manager\ deployments\ \fICOMMAND\fR [\fB\-\-api\-version\fR\ \fIAPI_VERSION\fR;\ default="v1beta2"] [\fB\-\-format\fR\ \fIFORMAT\fR] [\fB\-\-help\fR] [\fB\-\-project\fR\ \fIPROJECT\fR] [\fB\-\-quiet\fR,\ \fB\-q\fR] \fB\-\-region\fR\ \fIREGION\fR [\fB\-h\fR]
.SH "DESCRIPTION"
.sp
Commands for Deployment Manager deployments\&.
.SH "FLAGS"
.PP
\fB\-\-region\fR \fIREGION\fR
.RS 4
Name of the region
.RE
.SS "GLOBAL FLAGS"
.PP
\fB\-\-api\-version\fR \fIAPI_VERSION\fR; default="v1beta2"
.RS 4
Optional API version\&.
.RE
.PP
\fB\-\-format\fR \fIFORMAT\fR
.RS 4
Specify a format for printed output\&. By default, a command\-specific human\-friendly output format is used\&. Setting this flag to one of the available options will serialize the result of the command in the chosen format and print it to stdout\&. Supported formats are:
json,
text,
yaml\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display detailed help\&.
.RE
.PP
\fB\-\-project\fR \fIPROJECT\fR
.RS 4
The Google Cloud Platform project name to use for this invocation\&. If omitted then the current project is assumed\&.
.RE
.PP
\fB\-\-quiet\fR, \fB\-q\fR
.RS 4
Disable all interactive prompts when running gcloud commands\&. If input is required, defaults will be used, or an error will be raised\&.
.RE
.PP
\fB\-h\fR
.RS 4
Print a summary help and exit\&.
.RE
.SH "COMMANDS"
.sp
\fICOMMAND\fR is one of the following:
.PP
\fBcreate\fR
.RS 4
Insert (Create) a deployment using a specified template\&.
.RE
.PP
\fBdelete\fR
.RS 4
Delete a deployment\&.
.RE
.PP
\fBget\fR
.RS 4
Gets information about a specific deployment\&.
.RE
.PP
\fBlist\fR
.RS 4
Lists all deployments for a given project\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBpreview\fR component\&. See installing components if it is not installed\&.
