.TH "GCLOUD PREVIEW INSTANCE-GROUPS REMOVE-SERVICE" "1" "" "" ""
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.nh
.ad l
.SH "NAME"
.HP
gcloud_preview_instance-groups_remove-service \- removes a service from an instance group or an instance in it
.SH "SYNOPSIS"
.HP
gcloud\ preview\ instance\-groups\ remove\-service\ \fINAME\fR [\fB\-\-api\-version\fR\ \fIAPI_VERSION\fR;\ default="v1beta2"] [\fB\-\-format\fR\ \fIFORMAT\fR] [\fB\-\-help\fR] [\fB\-\-instance\fR\ \fIINSTANCE\fR] [\fB\-\-project\fR\ \fIPROJECT\fR] [\fB\-\-quiet\fR,\ \fB\-q\fR] \fB\-\-service\fR\ \fISERVICE\fR [\fB\-h\fR]
.SH "DESCRIPTION"
.sp
This command removes a service (name and port) from one or all instances in an instance group\&.
.sp
By default, the service is removed from the instance group itself, which makes it take effect on all instances in the instance group\&. However, if the \-\-instance flag is provided, the service is only removed from the particular instance that is specified by the flag\&.
.sp
Please see the API documentation for more details\&.
.SH "POSITIONAL ARGUMENTS"
.PP
\fINAME\fR
.RS 4
Instance group name\&.
.RE
.SH "FLAGS"
.PP
\fB\-\-instance\fR \fIINSTANCE\fR
.RS 4
The name of the instance resource to remove the service from\&. If not specified, the service will be removed from all instances in the instance group\&.
.RE
.PP
\fB\-\-service\fR \fISERVICE\fR
.RS 4
Name of the service\&.
.RE
.SS "GLOBAL FLAGS"
.PP
\fB\-\-api\-version\fR \fIAPI_VERSION\fR; default="v1beta2"
.RS 4
Optional API version\&.
.RE
.PP
\fB\-\-format\fR \fIFORMAT\fR
.RS 4
Specify a format for printed output\&. By default, a command\-specific human\-friendly output format is used\&. Setting this flag to one of the available options will serialize the result of the command in the chosen format and print it to stdout\&. Supported formats are:
json,
text,
yaml\&.
.RE
.PP
\fB\-\-help\fR
.RS 4
Display detailed help\&.
.RE
.PP
\fB\-\-project\fR \fIPROJECT\fR
.RS 4
The Google Cloud Platform project name to use for this invocation\&. If omitted then the current project is assumed\&.
.RE
.PP
\fB\-\-quiet\fR, \fB\-q\fR
.RS 4
Disable all interactive prompts when running gcloud commands\&. If input is required, defaults will be used, or an error will be raised\&.
.RE
.PP
\fB\-h\fR
.RS 4
Print a summary help and exit\&.
.RE
.SH "NOTES"
.sp
This command is in the Google Cloud SDK \fBpreview\fR component\&. See installing components if it is not installed\&.
