wtf:
  colors:
    background: black
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
    checked: yellow
    highlight:
      fore: black
      back: gray
    rows:
      even: yellow
      odd: white
  grid:
    # How _wide_ the columns are, in terminal characters. In this case we have
    # four columns, each of which are 35 characters wide.
    columns: [35, 35, 35, 35]
    # How _high_ the rows are, in terminal lines. In this case we have four rows
    # that support ten line of text and one of four.
    rows: [10, 10, 10, 10, 4]
  refreshInterval: 1
  openFileUtil: "open"
  mods:
    # You can have multiple widgets of the same type.
    # The "key" is the name of the widget and the type is the actual
    # widget you want to implement.
    europe_time:
      title: "Europe"
      type: clocks
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        GMT: "Etc/GMT"
        Amsterdam: "Europe/Amsterdam"
        Berlin: "Europe/Berlin"
        Barcelona: "Europe/Madrid"
        Copenhagen: "Europe/Copenhagen"
        London: "Europe/London"
        Rome: "Europe/Rome"
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 15
      sort: "alphabetical"
    americas_time:
      title: "Americas"
      type: clocks
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        Eastern: "America/New_York"
        Central: "America/Chicago"
        Mountain: "America/Denver"
        Pacific: "America/Los_Angeles"
      position:
        top: 0
        left: 1
        height: 1
        width: 1
      refreshInterval: 15
      sort: "alphabetical"
    ip:
      type: ipinfo
      title: "My IP"
      colors:
        name: "lightblue"
        value: "white"
      enabled: true
      position:
        top: 0
        left: 2
        height: 1
        width: 2
      refreshInterval: 150
    battery:
      type: power
      title: "⚡️"
      enabled: true
      position:
        top: 1
        left: 0
        height: 1
        width: 1
      refreshInterval: 15
    news:
      type: hackernews
      title: "HackerNews"
      enabled: true
      numberOfStories: 10
      position:
        top: 1
        left: 1
        height: 1
        width: 3
      storyType: top
      refreshInterval: 900
    security:
      enabled: true
      position:
        top: 2
        left: 0
        height: 1
        width: 1
      refreshInterval: 3600
    github:
      apiKey: "f4680f5689f7d2105f90496ef8b417873e838bbd"
      baseURL: ""
      enabled: true
      enableStatus: true
      customQueries:
        othersPRs:
          title: "Others' Pull Requests"
          filter: "is:open is:pr -author:christianromney"
      position:
        top: 2
        left: 1
        height: 2
        width: 3
      refreshInterval: 300
      repositories:
        pantry: "pantry"
        bengal: "bengal"
        salk: "salk"
      uploadURL: ""
      username: "reifyhealth"
