language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
  - sudo add-apt-repository -y ppa:fish-shell/release-2
  - sudo apt-get update
  - sudo apt-get -y install fish

script: make test
